<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite ignored="0" hostname="Qualitrix-LinuxPC" failures="1" tests="1" name="org.testscript.coursepage.VerifyUserIsAbleToViewEditSearchAndDeleteTheNotes" time="231.109" errors="0" timestamp="24 Apr 2019 22:21:57 GMT" skipped="0">
  <testcase classname="org.testscript.coursepage.VerifyUserIsAbleToViewEditSearchAndDeleteTheNotes" name="verifyViewEditSearchDeletingOfNotes" time="231.109">
    <failure message="Could not get content to which User is enrolled" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Could not get content to which User is enrolled
	at org.testng.Assert.fail(Assert.java:94)
	at org.pageobjects.WorkspacePageObj.getContentFromMyCourses(WorkspacePageObj.java:1545)
	at org.testscript.coursepage.VerifyUserIsAbleToViewEditSearchAndDeleteTheNotes.verifyViewEditSearchDeletingOfNotes(VerifyUserIsAbleToViewEditSearchAndDeleteTheNotes.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyViewEditSearchDeletingOfNotes -->
</testsuite> <!-- org.testscript.coursepage.VerifyUserIsAbleToViewEditSearchAndDeleteTheNotes -->
